#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'migratoryBirds' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def migratoryBirds(arr):
     dictn={}
    for item in arr:
        if item in dictn:
            dictn[item]+=1
        else:
            dictn[item]=1
    
    max_=0
    for key, values in dictn.items():
        if (values>max_):
            max_=values
            number=key
        elif (values==max_):
            if (key<number):
                number=key
    
    return number

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
